package com.purnaprasanth.githubusers

import com.purnaprasanth.githubusers.data.model.GitRepo
import com.purnaprasanth.githubusers.data.model.GitUser
import com.purnaprasanth.githubusers.github.data.GitHubRepo
import com.purnaprasanth.githubusers.github.data.GitHubUser
import com.purnaprasanth.githubusers.github.data.License
import com.purnaprasanth.githubusers.github.data.Owner

/**
 * Created by Purna on 2019-09-24 as a part of GithubUsers
 **/

val gitHubUser = GitHubUser(
    login = "octocat",
    id = 583231,
    nodeId = "MDQ6VXNlcjU4MzIzMQ==",
    avatarUrl = "https://avatars3.githubusercontent.com/u/583231?v=4",
    gravatarId = "",
    url = "https://api.github.com/users/octocat",
    htmlUrl = "https://github.com/octocat",
    followersUrl = "https://api.github.com/users/octocat/followers",
    followingUrl = "https://api.github.com/users/octocat/following{/other_user}",
    gistsUrl = "https://api.github.com/users/octocat/gists{/gist_id}",
    starredUrl = "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    subscriptionsUrl = "https://api.github.com/users/octocat/subscriptions",
    organizationsUrl = "https://api.github.com/users/octocat/orgs",
    reposUrl = "https://api.github.com/users/octocat/repos",
    eventsUrl = "https://api.github.com/users/octocat/events{/privacy}",
    receivedEventsUrl = "https://api.github.com/users/octocat/received_events",
    type = "User",
    siteAdmin = false,
    name = "The Octocat",
    company = "GitHub",
    blog = "http://www.github.com/blog",
    location = "San Francisco",
    email = null,
    hireable = null,
    bio = null,
    publicRepos = 8,
    publicGists = 8,
    followers = 2761,
    following = 9,
    createdAt = "2011-01-25T18:44:36Z",
    updatedAt = "2019-09-23T14:29:34Z"
)

val gitHubRepo1 = GitHubRepo(
    id = 132935648,
    nodeId = "MDEwOlJlcG9zaXRvcnkxMzI5MzU2NDg=",
    name = "boysenberry-repo-1",
    fullName = "octocat/boysenberry-repo-1",
    private = false,
    owner = Owner(
        login = "octocat",
        id = 583231,
        nodeId = "MDQ6VXNlcjU4MzIzMQ==",
        avatarUrl = "https://avatars3.githubusercontent.com/u/583231?v=4",
        gravatarId = "",
        url = "https://api.github.com/users/octocat",
        htmlUrl = "https://github.com/octocat",
        followersUrl = "https://api.github.com/users/octocat/followers",
        followingUrl = "https://api.github.com/users/octocat/following{/other_user}",
        gistsUrl = "https://api.github.com/users/octocat/gists{/gist_id}",
        starredUrl = "https://api.github.com/users/octocat/starred{/owner}{/repo}",
        subscriptionsUrl = "https://api.github.com/users/octocat/subscriptions",
        organizationsUrl = "https://api.github.com/users/octocat/orgs",
        reposUrl = "https://api.github.com/users/octocat/repos",
        eventsUrl = "https://api.github.com/users/octocat/events{/privacy}",
        receivedEventsUrl = "https://api.github.com/users/octocat/received_events",
        type = "User",
        siteAdmin = false
    ),
    htmlUrl = "https://github.com/octocat/boysenberry-repo-1",
    description = "Testing",
    fork = true,
    url = "https://api.github.com/repos/octocat/boysenberry-repo-1",
    forksUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/forks",
    keysUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/keys{/key_id}",
    collaboratorsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/collaborators{/collaborator}",
    teamsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/teams",
    hooksUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/hooks",
    issueEventsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/issues/events{/number}",
    eventsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/events",
    assigneesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/assignees{/user}",
    branchesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/branches{/branch}",
    tagsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/tags",
    blobsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/git/blobs{/sha}",
    gitRefsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/git/refs{/sha}",
    treesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/git/trees{/sha}",
    gitTagsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/git/tags{/sha}",
    statusesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/statuses/{sha}",
    languagesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/languages",
    stargazersUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/stargazers",
    contributorsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/contributors",
    subscribersUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/subscribers",
    subscriptionUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/subscription",
    commitsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/commits{/sha}",
    gitCommitsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/git/commits{/sha}",
    commentsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/comments{/number}",
    issueCommentUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/issues/comments{/number}",
    contentsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/contents/{+path}",
    compareUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/compare/{base}...{head}",
    mergesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/merges",
    archiveUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/{archive_format}{/ref}",
    downloadsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/downloads",
    issuesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/issues{/number}",
    pullsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/pulls{/number}",
    milestonesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/milestones{/number}",
    notificationsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/notifications{?since,all,participating}",
    labelsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/labels{/name}",
    releasesUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/releases{/id}",
    deploymentsUrl = "https://api.github.com/repos/octocat/boysenberry-repo-1/deployments",
    createdAt = "2018-05-10T17:51:29Z",
    updatedAt = "2019-09-12T16:21:29Z",
    pushedAt = "2018-05-10T17:52:17Z",
    gitUrl = "git://github.com/octocat/boysenberry-repo-1.git",
    sshUrl = "git@github.com:octocat/boysenberry-repo-1.git",
    cloneUrl = "https://github.com/octocat/boysenberry-repo-1.git",
    svnUrl = "https://github.com/octocat/boysenberry-repo-1",
    homepage = "",
    size = 4,
    stargazersCount = 2,
    watchersCount = 2,
    language = null,
    hasIssues = false,
    hasProjects = true,
    hasDownloads = true,
    hasWiki = true,
    hasPages = false,
    forksCount = 4,
    mirrorUrl = null,
    archived = false,
    disabled = false,
    openIssuesCount = 0,
    license = null,
    forks = 4,
    openIssues = 0,
    watchers = 2,
    defaultBranch = "master"
)

val gitHubRepo2 = GitHubRepo(
    id = 18221276,
    nodeId = "MDEwOlJlcG9zaXRvcnkxODIyMTI3Ng==",
    name = "git-consortium",
    fullName = "octocat/git-consortium",
    private = false,
    owner = Owner(
        login = "octocat",
        id = 583231,
        nodeId = "MDQ6VXNlcjU4MzIzMQ==",
        avatarUrl = "https://avatars3.githubusercontent.com/u/583231?v=4",
        gravatarId = "",
        url = "https://api.github.com/users/octocat",
        htmlUrl = "https://github.com/octocat",
        followersUrl = "https://api.github.com/users/octocat/followers",
        followingUrl = "https://api.github.com/users/octocat/following{/other_user}",
        gistsUrl = "https://api.github.com/users/octocat/gists{/gist_id}",
        starredUrl = "https://api.github.com/users/octocat/starred{/owner}{/repo}",
        subscriptionsUrl = "https://api.github.com/users/octocat/subscriptions",
        organizationsUrl = "https://api.github.com/users/octocat/orgs",
        reposUrl = "https://api.github.com/users/octocat/repos",
        eventsUrl = "https://api.github.com/users/octocat/events{/privacy}",
        receivedEventsUrl = "https://api.github.com/users/octocat/received_events",
        type = "User",
        siteAdmin = false
    ),
    htmlUrl = "https://github.com/octocat/git-consortium",
    description = "This repo is for demonstration purposes only.",
    fork = false,
    url = "https://api.github.com/repos/octocat/git-consortium",
    forksUrl = "https://api.github.com/repos/octocat/git-consortium/forks",
    keysUrl = "https://api.github.com/repos/octocat/git-consortium/keys{/key_id}",
    collaboratorsUrl = "https://api.github.com/repos/octocat/git-consortium/collaborators{/collaborator}",
    teamsUrl = "https://api.github.com/repos/octocat/git-consortium/teams",
    hooksUrl = "https://api.github.com/repos/octocat/git-consortium/hooks",
    issueEventsUrl = "https://api.github.com/repos/octocat/git-consortium/issues/events{/number}",
    eventsUrl = "https://api.github.com/repos/octocat/git-consortium/events",
    assigneesUrl = "https://api.github.com/repos/octocat/git-consortium/assignees{/user}",
    branchesUrl = "https://api.github.com/repos/octocat/git-consortium/branches{/branch}",
    tagsUrl = "https://api.github.com/repos/octocat/git-consortium/tags",
    blobsUrl = "https://api.github.com/repos/octocat/git-consortium/git/blobs{/sha}",
    gitTagsUrl = "https://api.github.com/repos/octocat/git-consortium/git/tags{/sha}",
    gitRefsUrl = "https://api.github.com/repos/octocat/git-consortium/git/refs{/sha}",
    treesUrl = "https://api.github.com/repos/octocat/git-consortium/git/trees{/sha}",
    statusesUrl = "https://api.github.com/repos/octocat/git-consortium/statuses/{sha}",
    languagesUrl = "https://api.github.com/repos/octocat/git-consortium/languages",
    stargazersUrl = "https://api.github.com/repos/octocat/git-consortium/stargazers",
    contributorsUrl = "https://api.github.com/repos/octocat/git-consortium/contributors",
    subscribersUrl = "https://api.github.com/repos/octocat/git-consortium/subscribers",
    subscriptionUrl = "https://api.github.com/repos/octocat/git-consortium/subscription",
    commitsUrl = "https://api.github.com/repos/octocat/git-consortium/commits{/sha}",
    gitCommitsUrl = "https://api.github.com/repos/octocat/git-consortium/git/commits{/sha}",
    commentsUrl = "https://api.github.com/repos/octocat/git-consortium/comments{/number}",
    issueCommentUrl = "https://api.github.com/repos/octocat/git-consortium/issues/comments{/number}",
    contentsUrl = "https://api.github.com/repos/octocat/git-consortium/contents/{+path}",
    compareUrl = "https://api.github.com/repos/octocat/git-consortium/compare/{base}...{head}",
    mergesUrl = "https://api.github.com/repos/octocat/git-consortium/merges",
    archiveUrl = "https://api.github.com/repos/octocat/git-consortium/{archive_format}{/ref}",
    downloadsUrl = "https://api.github.com/repos/octocat/git-consortium/downloads",
    issuesUrl = "https://api.github.com/repos/octocat/git-consortium/issues{/number}",
    pullsUrl = "https://api.github.com/repos/octocat/git-consortium/pulls{/number}",
    milestonesUrl = "https://api.github.com/repos/octocat/git-consortium/milestones{/number}",
    notificationsUrl = "https://api.github.com/repos/octocat/git-consortium/notifications{?since,all,participating}",
    labelsUrl = "https://api.github.com/repos/octocat/git-consortium/labels{/name}",
    releasesUrl = "https://api.github.com/repos/octocat/git-consortium/releases{/id}",
    deploymentsUrl = "https://api.github.com/repos/octocat/git-consortium/deployments",
    createdAt = "2014-03-28T17:55:38Z",
    updatedAt = "2019-03-26T02:39:00Z",
    pushedAt = "2019-07-22T17:15:38Z",
    gitUrl = "git://github.com/octocat/git-consortium.git",
    sshUrl = "git@github.com:octocat/git-consortium.git",
    cloneUrl = "https://github.com/octocat/git-consortium.git",
    svnUrl = "https://github.com/octocat/git-consortium",
    homepage = null,
    size = 190,
    stargazersCount = 9,
    watchersCount = 9,
    language = null,
    hasIssues = true,
    hasProjects = true,
    hasDownloads = true,
    hasWiki = true,
    hasPages = false,
    forksCount = 34,
    mirrorUrl = null,
    archived = false,
    disabled = false,
    openIssuesCount = 32,
    license = License(
        key = "mit",
        name = "MIT License",
        spdxId = "MIT",
        url = "https://api.github.com/licenses/mit",
        nodeId = "MDc6TGljZW5zZTEz"
    ),
    forks = 34,
    openIssues = 32,
    watchers = 9,
    defaultBranch = "master"
)

val gitRepo1 = GitRepo(
    name = "boysenberry-repo-1",
    description = "Testing",
    link = "https://github.com/octocat/boysenberry-repo-1",
    starsCount = 2
)

val gitRepo2 = GitRepo(
    name = "git-consortium",
    description = "This repo is for demonstration purposes only.",
    link = "https://github.com/octocat/git-consortium",
    starsCount = 9
)

val gitUser = GitUser(
    name = "The Octocat",
    userName = "octocat",
    photo = "https://avatars3.githubusercontent.com/u/583231?v=4",
    repos = listOf(gitRepo1, gitRepo2)
)